step 2 failure

diff --git a/.github/workflows/status-check.yml b/.github/workflows/status-check.yml
--- a/.github/workflows/status-check.yml
+++ b/.github/workflows/status-check.yml
@@ -8,9 +8,12 @@ jobs:
         steps:
             - name: Step 1
               run: sleep 20
+            - name: Step 2
+              id: step2
+              run: exit 1
             - name: Runs on failure
-              if: failure()
-              run: echo "This job ran on failure"
+              if: failure() && steps.step2.conclusion == 'failure'
+              run: echo "Stepp 2 has failed"
             - name: Runs on success
               if: success()
               run: echo "This job ran on success"
